//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HojaResumen.Modelo.BaseDatosT
{
    using System;
    using System.Collections.Generic;
    
    public partial class AudiTrail
    {
        public int Id { get; set; }
        public string Usuario { get; set; }
        public string Tabla { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public string Evento { get; set; }
        public string Campo { get; set; }
        public string Valor { get; set; }
        public string ValorActualizado { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> Tiempo { get; set; }
    }
}
