//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HojaResumen.Modelo.BaseDatosT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CicloAutoclave : DbContext
    {
        public CicloAutoclave()
            : base("name=CicloAutoclave")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CiclosAutoclaves> CiclosAutoclaves { get; set; }
        public virtual DbSet<CiclosSabiDos> CiclosSabiDos { get; set; }
        public virtual DbSet<MaestroAutoclave> MaestroAutoclave { get; set; }
        public virtual DbSet<Parametros> Parametros { get; set; }
        public virtual DbSet<AudiTrail> AudiTrail { get; set; }
        public virtual DbSet<Agua> Agua { get; set; }
        public virtual DbSet<Vapor> Vapor { get; set; }
    }
}
