//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HojaResumen.Modelo.BaseDatosT
{
    using System;
    using System.Collections.Generic;
    
    public partial class CiclosSabiDos
    {
        public int Id { get; set; }
        public string IdAutoclave { get; set; }
        public string IdSeccion { get; set; }
        public string TInicio { get; set; }
        public string NumeroCiclo { get; set; }
        public string Programa { get; set; }
        public string Modelo { get; set; }
        public string Programador { get; set; }
        public string Operador { get; set; }
        public string CodigoProducto { get; set; }
        public string Lote { get; set; }
        public string Notas { get; set; }
        public string IdUsuario { get; set; }
        public string Fase1 { get; set; }
        public string DuracionTotalF1 { get; set; }
        public string Fase2 { get; set; }
        public string DuracionTotalF2 { get; set; }
        public string TIF2 { get; set; }
        public string TISubF2 { get; set; }
        public string TFF2 { get; set; }
        public string TFSubF2 { get; set; }
        public string Fase3 { get; set; }
        public string DuracionTotalF3 { get; set; }
        public string TIF3 { get; set; }
        public string TISubF3 { get; set; }
        public string TFF3 { get; set; }
        public string TFSubF3 { get; set; }
        public string Fase4 { get; set; }
        public string DuracionTotalF4 { get; set; }
        public string TIF4 { get; set; }
        public string TISubF4 { get; set; }
        public string Fase5 { get; set; }
        public string DuracionTotalF5 { get; set; }
        public string Fase6 { get; set; }
        public string DuracionTotalF6 { get; set; }
        public string Fase7A { get; set; }
        public string DuracionTotalF7A { get; set; }
        public string Fase8A { get; set; }
        public string DuracionTotalF8A { get; set; }
        public string Fase7B { get; set; }
        public string DuracionTotalF7B { get; set; }
        public string Fase8B { get; set; }
        public string DuracionTotalF8B { get; set; }
        public string Fase9 { get; set; }
        public string DuracionTotalF9 { get; set; }
        public string TIF9 { get; set; }
        public string TISubF9 { get; set; }
        public string TFF9 { get; set; }
        public string Fase10 { get; set; }
        public string DuracionTotalF10 { get; set; }
        public string Fase11 { get; set; }
        public string DuracionTotalF11 { get; set; }
        public string Fase12 { get; set; }
        public string TIF12 { get; set; }
        public string TISubF12 { get; set; }
        public string HoraInicio { get; set; }
        public string HoraFin { get; set; }
        public string EsterilizacionN { get; set; }
        public string TMinima { get; set; }
        public string TMaxima { get; set; }
        public string DuracionTotal { get; set; }
        public string FtzMin { get; set; }
        public string FtzMax { get; set; }
        public string AperturaPuerta { get; set; }
        public string TiempoCiclo { get; set; }
        public string ErrorCiclo { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string DifMaxMin { get; set; }
    }
}
