//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HojaResumen.Modelo.BaseDatosT
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroAutoclave
    {
        public int Id { get; set; }
        public string Matricula { get; set; }
        public string Nombre { get; set; }
        public int Version { get; set; }
        public string IP { get; set; }
        public string Seccion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string UltimoCiclo { get; set; }
        public string RutaSalida { get; set; }
        public string RutaSalidaPDF { get; set; }
    }
}
