//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HojaResumen.Modelo.BaseDatosT
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaestroAutoclave
    {
        public int Id { get; set; }
        public string Matricula { get; set; }
        public string Nombre { get; set; }
        public int Version { get; set; }
        public string IP { get; set; }
        public string Seccion { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string UltimoCiclo { get; set; }
        public string RutaSalida { get; set; }
    }
}
