//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HojaResumen.Modelo.BaseDatosT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametros
    {
        public int Id { get; set; }
        public string ImpresoraSabiUno { get; set; }
        public string ImpresoraSabiDos { get; set; }
        public string RutaLog { get; set; }
        public int Tiempo { get; set; }
        public Nullable<bool> Reinicio { get; set; }
        public Nullable<int> TSesion { get; set; }
        public string GUsers { get; set; }
        public string GSupervisors { get; set; }
        public string GAdmins { get; set; }
    }
}
